CREATE TABLE users (
id SERIAL PRIMARY KEY,
username VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE tracker (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id),
sleep INTEGER DEFAULT 0,
steps INTEGER DEFAULT 0,
water INTEGER DEFAULT 0,
food INTEGER DEFAULT 0,
workout INTEGER DEFAULT 0
);